### PR TITLE
refactor!: use sdk provided filesystem util, remove aeproject util implementation

### LINKED ISSUE #474: use getFilesystem as exposed by the sdk

### PR DESCRIPTION
**Pull request by thepiwo**
closes #474

### CODE REVIEW

**Comment by thepiwo** [comment]
`getFileSystem` as exposed by the sdk is async so this will need to be a breaking change or some workaround...

**Comment by marc0olo** [comment]
> `getFileSystem` as exposed by the sdk is async so this will need to be a breaking change or some workaround...

did you ask @davidyuk why it is async? 🤔

**Comment by davidyuk** [comment]
I've used non-blocking file access api, this way nodes process may request multiple files at once

**Comment by thepiwo** [comment]
I made this PR breaking and will gather some more breaking changes eventually for an upcoming v5

**Comment by thepiwo** [comment]
released in https://github.com/aeternity/aeproject/releases/tag/v5.0.0

**Pull request closed without merging**
